# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bfdc479686f2569ccd1d4c1a16a2d13c9c11ea3a123008cf73a36be277dd2032f2e2c572d8536b158eadd349da7f396f6ef3d83a2dc85f46dfa68912ef8adab

test:
  secret_key_base: d6b92dc384a5f0dfe97a8c6fc59e29d793fc079e769e80f26f24578cd85e0627dd17b795a2b2711caa290f1b01acc533d102d7427d22911109cc2e03ece10d3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
